version: "3.7"
name: fs-core-challenge
services:
  postgres:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chat-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - spring-react-network
  spring-app:
    build:
      context: ../server
    container_name: server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chat-app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
    depends_on:
      - postgres
    networks:
      - spring-react-network
  react-app:
    build:
      context: ../client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - spring-app
    networks:
      - spring-react-network
networks:
  spring-react-network:
    driver: bridge
